#!/bin/sh

case "$1" in
    # startup - load scull, load faulty driver, modprobe on hello module
    start)
        echo "Loading modules"
        scull_load
        faulty_driver_load
        modprobe hello
        ;;
    # shutdown - unload scull, unload faulty driver, rmmod on hello module
    stop)
        echo "Unloading modules"
        scull_unload
        faulty_driver_unload
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac