#!/bin/sh

# startup - load scull, load faulty driver, modprobe on hello module
# shutdown - unload scull, unload faulty driver, rmmod on hello module

case "$1" in
    # Start aesdsocket in daemon mode
    start)
        echo "Loading modules"
        scull_load
        faulty_driver_load
        modprobe hello
        ;;
    # Stop aesdsocket and send SIGTERM
    stop)
        echo "Unloading modules"
        scull_unload
        faulty_driver_unload
        rmmod hello
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac